INSERT INTO public.genre(id_genre, nom)
VALUES (1, 'Action'),
    (2, 'RPG'),
    (3, 'Adventure'),
    (4, 'Puzzle'),
    (5, 'Simulation'),
    (6, 'Strategy'),
    (7, 'Sports'),
    (8, 'Shooter'),
    (9, 'Fighting'),
    (10, 'Platformer'),
    (11, 'Racing'),
    (12, 'Survival'),
    (13, 'Horror'),
    (14, 'Sandbox'),
    (15, 'Idle'),
    (16, 'MMORPG'),
    (17, 'Rogue-like'),
    (18, 'Card Game'),
    (19, 'Trivia'),
    (20, 'Music/Rhythm');
